sudo: required
language: generic
services:
  - docker

before-install:
  - docker build -t test_image -f Dockerfile.dev .
  
script:
  - docker run -e CI=true test_image npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-458512962315'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY